#!/usr/bin/env python

import os
import shutil

HOME = os.getenv('HOME') or ''

def do_check(name, test, help_url):
    if test:
        return True
    else:
        print(f'{name} is not installed: {help_url}')
        return False

def run_checks():
    success = True
    success &= do_check('Zsh', shutil.which('zsh'), 'https://ohmyz.sh/#install')
    success &= do_check('Oh-My-Zsh', os.path.exists(os.path.join(HOME, '.oh-my-zsh')), 'https://ohmyz.sh/#install')
    success &= do_check('Zsh Autosuggestions', os.path.exists(os.path.join(HOME, '.oh-my-zsh', 'custom', 'plugins', 'zsh-autosuggestions')), 'https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#oh-my-zsh')
    success &= do_check('Powerlevel10k', os.path.exists(os.path.join(HOME, '.oh-my-zsh', 'custom', 'themes', 'powerlevel10k')), 'https://github.com/romkatv/powerlevel10k#oh-my-zsh')
    success &= do_check('Neovim', shutil.which('nvim') is not None, 'https://neovim.io')
    success &= do_check('LunarVim', os.path.exists(os.path.join(HOME, '.local', 'share', 'lunarvim')), 'https://www.lunarvim.org/docs/installation')
    success &= do_check('Kitty', shutil.which('kitty') is not None, 'https://sw.kovidgoyal.net/kitty/quickstart/')
    if success:
        print('All dependencies installed!')
    else:
        print("Some dependencies aren't installed yet.")
    return success

def install_dotfile(system_path, repo_path):
    original_system_path = system_path
    system_path = os.path.realpath(system_path)
    repo_path = os.path.realpath(repo_path)
    if system_path == repo_path:
        print(f'{original_system_path} already points to dotfiles repo')
        return
    else:
        if os.path.exists(system_path):
            print(f'{original_system_path} already exists. Backing up to {original_system_path}.bak')
            os.rename(system_path, system_path+'.bak')
        print(f'Creating symlink from {system_path} to {repo_path}')
        os.symlink(repo_path, system_path)


def install_dotfiles():
    install_dotfile(os.path.join(HOME, '.zshrc'), 'zshrc')
    install_dotfile(os.path.join(HOME, '.config', 'kitty', 'kitty.conf'), 'kitty.conf')
    install_dotfile(os.path.join(HOME, '.config', 'kitty', 'lunar.conf'), 'lunar.conf')
    install_dotfile(os.path.join(HOME, '.config', 'lvim', 'config.lua'), 'config.lua')

def main():
    checks_passed = run_checks()
    if checks_passed:
        install_dotfiles()

if __name__ == "__main__":
    main()
